name: Build & Release app

on:
  push:
    branches: ['main']
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    name: Install dependencies and build preact
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cache-node.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.11.0'

      - name: Cache node_modules
        id: cache-node
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Set env
        run: |
          echo "ENCRYPTION_KEY=${{ secrets.ENCRYPTION_KEY }}" > .env.local

      - name: Set secret env
        run: |
          echo "SECRET_KEY=${{ secrets.SECRET_KEY }}" > src/electron/.env

      - name: Decrypt encription logic
        run: node secureFile.cjs -d src/electron/utils/encryption.cjs.enc

      - name: Build preact
        run: npm run build

      - name: Upload built source for other jobs
        uses: actions/upload-artifact@v4
        with:
          name: built-src
          path: |
            node_modules
            dist
            src
            package.json
            package-lock.json

  build-macos:
    name: Build macOS
    runs-on: macos-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Download built source
        uses: actions/download-artifact@v4
        with:
          name: built-src
          path: .

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.11.0'

      - name: Install dependencies (skip if cached)
        run: npm ci

      - name: Rebuild native modules
        run: npm run rebuild

      - name: Package app
        run: npm run make

      - name: Upload macOS artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64
          path: out/make

  build-windows:
    name: Build Windows
    runs-on: windows-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Download built source
        uses: actions/download-artifact@v4
        with:
          name: built-src
          path: .

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.11.0'

      - name: Install dependencies
        run: npm ci

      - name: Rebuild native modules
        run: npm run rebuild

      - name: Package app
        run: npm run make

      - name: Upload Windows artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-x64
          path: out/make

  build-linux:
    name: Build Linux
    runs-on: ubuntu-latest
    continue-on-error: true
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Install RPM build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            rpm \
            fakeroot \
            libarchive-tools \
            dpkg-dev \
            build-essential

      - name: Download built source
        uses: actions/download-artifact@v4
        with:
          name: built-src
          path: .

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23.11.0'

      - name: Install dependencies
        run: npm ci

      - name: Rebuild native modules
        run: npm run rebuild

      - name: Package app (make .deb, .AppImage, etc.)
        run: npm run make

      - name: Upload Linux artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-x64
          path: out/make

  release:
    name: Create GitHub Release & upload binaries
    runs-on: ubuntu-latest
    needs: [build-macos, build-windows, build-linux]
    steps:
      - uses: actions/checkout@v4

      - name: Download macOS arm64
        uses: actions/download-artifact@v4
        with:
          name: macos-arm64
          path: ./out/make/macos-arm64

      - name: Download Windows x64
        uses: actions/download-artifact@v4
        with:
          name: windows-x64
          path: ./out/make/windows-x64

      - name: Download Linux x64
        continue-on-error: true
        uses: actions/download-artifact@v4
        with:
          name: linux-x64
          path: ./out/make/linux-x64

      - name: log files
        run: find ./out/make -maxdepth 5

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          body: |
            Automated build release for tag ${{ github.ref_name }}

      - name: Find macOS DMG file
        id: find_dmg
        run: |
          file_path=$(find ./out/make/macos-arm64 -type f -name '*.dmg' | head -n 1)
          echo "Found file: $file_path"
          echo "path=$file_path" >> "$GITHUB_OUTPUT"

      - name: Upload macos arm64 asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_dmg.outputs.path }}
          asset_name: app-macos.dmg
          asset_content_type: application/octet-stream

      - name: Find windows EXE file
        id: find_exe
        run: |
          file_path=$(find ./out/make/windows-x64 -type f -name '*.exe' | head -n 1)
          echo "Found file: $file_path"
          echo "path=$file_path" >> "$GITHUB_OUTPUT"

      - name: Upload Windows x64 assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_exe.outputs.path }}
          asset_name: app-windows.exe
          asset_content_type: application/octet-stream

      - name: Find Linux DEB file
        id: find_deb
        run: |
          file_path=$(find ./out/make/linux-x64 -type f -name '*.deb' | head -n 1)
          echo "Found file: $file_path"
          echo "path=$file_path" >> "$GITHUB_OUTPUT"

      - name: Upload Linux .deb asset
        continue-on-error: true
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_deb.outputs.path }}
          asset_name: app-linux.deb
          asset_content_type: application/vnd.debian.binary-package

      # - name: Upload Linux .AppImage asset
      #   continue-on-error: true
      #   uses: actions/upload-release-asset@v1
      #   with:
      #     upload_url:  steps.create_release.outputs.upload_url 
      #     asset_path: ./out/make/linux/**/*.AppImage
      #     asset_name: app-linux.AppImage
      #     asset_content_type: application/octet-stream

      - name: Find Linux RPM file
        id: find_rpm
        run: |
          file_path=$(find ./out/make/linux-x64 -type f -name '*.rpm' | head -n 1)
          echo "Found file: $file_path"
          echo "path=$file_path" >> "$GITHUB_OUTPUT"

      - name: Upload Linux .rpm asset
        continue-on-error: true
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.find_rpm.outputs.path }}
          asset_name: app-linux.rpm
          asset_content_type: application/x-rpm